apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: YXBwdXNlcg==         # Base64 encoded 'appuser'
  password: YXBwcGFzc3dvcmQ=     # Base64 encoded 'apppassword'
  root-password: c2VjdXJlcGFzcw== # Base64 encoded 'securepass'

